### ISSUE TITLE
Comparison of isoform/bin stability

### ISSUE THREAD

**Issue by aleighbrown** [isaacvock/fastq2EZbakR#19]
Hello, 

I'm interested in comparing the stability of different 3'UTRs within the same conditions. We've done a pulse-labelling approach with NTR-seq/SLAM-seq (just T>C + IAA) and we're trying to estimate the half-life of these 2 different UTRs within 2 different conditions, but primarily focused on comparing the stability of the bins to one another within the same condition. 

I thought the DEXseq's exon-bin counting approach would be appropriate for this and I've extracted what I believe to be the relevant 'fraction new rna'. I'm using the results of `EZbakR::EstimateFractions` as input, primarily using the `fraction_highTC` and `se_logit_fraction_highTC` to estimate a decay constant + half-life for each bin, using the `se_logit_fraction_highTC` in a sort of crude inverse-variance weighting approach.

I was wondering if you've had any thought to how to perform these sort of analyses and the validity of the current approach. 

Code below gives an approach for 1 UTR that we're interested in 

```
library(dplyr)
library(tidyr)
library(readr)
library(EZbakR)
library(ggplot2)
library(nls2)

# Function to estimate half-life using weighted regression
estimate_half_life_weighted <- function(data, 
                                        time_col = "tl", 
                                        logit_fraction_col = "logit_fraction_highTC", 
                                        se_logit_fraction_col = "se_logit_fraction_highTC", 
                                        group_col = "group") {
  
  # Transform the logit fraction and calculate weights
  data <- data %>%
    mutate(
      fraction_highTC = exp(!!sym(logit_fraction_col)) / (1 + exp(!!sym(logit_fraction_col))),
      fraction_remaining = 1 - fraction_highTC,
      weight = 1 / (!!sym(se_logit_fraction_col))^2  # Inverse variance as weight - not sure how I feel about this given it's in logit...
    )
  

  result <- data %>%
    group_by(across(all_of(group_col))) %>%
    summarise(
      # grouped nls regression
      results = list(purrr::map(
        list(cur_data()), ~ {
          decay_model <- nls(
            formula = fraction_remaining ~ exp(-k * !!sym(time_col)),
            start = list(k = 0.1),
            data = .x,
            weights = .x$weight
          )
          
          # Calculate the confidence intervals for the decay constant `k`
          ci_k <- confint(decay_model, parm = "k")
          
          # Return the `k` value and its confidence intervals 
          tibble(
            decay_constant = coef(decay_model)["k"],
            ci_decay_constant_lower = ci_k[1],
            ci_decay_constant_upper = ci_k[2]
          )
        })
      )
    ) %>%
    unnest(results) %>% unnest()  # Unnest the results to return k and ci_k columns
  
  result = result  %>% 
    mutate(across(c(decay_constant, ci_decay_constant_lower, 
                    ci_decay_constant_upper), ~ log(2) / .x, .names = "half_life_{.col}")) %>% # calculate half-life - give some better names
    dplyr::rename(half_life = half_life_decay_constant,
                  half_life_upper_estimate = half_life_ci_decay_constant_lower,
                  half_life_lower_estimate = half_life_ci_decay_constant_upper)
  return(result)
}

elk1_bins = ezbdo$fractions$rname_exonbin_sj %>%  
  filter(sj != TRUE) %>% 
  mutate(exon_bin = case_when(
  exon_bin == 'EENSG00000126767.18_2__distal+ENSG00000126767.18_2002' ~ "short only",
  exon_bin == 'EENSG00000126767.18_2__distal+ENSG00000126767.18_2001' ~ "long only",
  TRUE ~ "other")) %>% 
  filter(exon_bin != "other") %>% 
  separate(sample, into = c("cond",'rep','tl')) %>% 
  mutate(tl = parse_number(tl)) %>% 
  mutate(fraction_remaining = 1 - fraction_highTC) %>% 
  select(tl,cond,rep,fraction_remaining,exon_bin,fraction_highTC,logit_fraction_highTC,se_logit_fraction_highTC,n)

# just ELK1
check2 = estimate_half_life_weighted(data = elk1_bins, 
                                     time_col = 'tl', 
                                     group_col = c('exon_bin', 'cond'))
```

**Comment by isaacvock** [comment]
This strategy should work, my main comments are:

1) I'd suggest fitting the log(kdeg) in your nonlinear least squares call, it won't make a huge difference but the statistics will typically work out nicer when you are working with unbounded parameters.
2) Weighting data points by the inverse logit(fraction new) variance should be fine. There are some simple approximation schemes you could use to figure out what the variance is on the natural fraction new scale, but I don't think it will make much of a difference. 

I'll note for others interested in this kind of analysis that it is also possible to use the generalized dynamical systems modeling in EZbakR to do this multi-label time integration. See [the vignette](https://isaacvock.github.io/EZbakR/articles/EZDynamics.html) for some details, though this case would be a much simpler model that any discussed in that vignette.

Best,
Isaac
