### ISSUE TITLE
Skipping index building and fastp trimming?

### ISSUE THREAD

**Issue by aleighbrown** [isaacvock/fastq2EZbakR#7]
fantastic pipeline, so well documented

extremely minor feature request, but allowing fastp trimming and index building (star, hisat2) to be skipped if the indexes and trimmed files already exist would be nice

(resolved with some symlinks)

thanks

**Comment by isaacvock** [comment]
Thank you for the kind words and good suggestions, I have started working on the first (#8) and will tackle the second once that is finished.

Tasks:

- [ ] allow skipping of trimming
- [ ] allow skipping of index creation 

Best,
Isaac

**Comment by isaacvock** [comment]
Alright, this should be good now. There is a new parameter in the config (`skip_trimming`) that can be set to TRUE to skip fastp trimming. The indexing problem shouldn't have been a problem, but there were some bugs that would cause unnecessary re-indexing even if an index already existed. These have been fixed.

Let me know if you run into any problems or have any additional suggestions,
Isaac
